### ISSUE TITLE
I need help accessing USB camera input buttons and trigger events

### ISSUE THREAD

**Issue by jprules321** [node-usb/node-usb#320]
I've crawled google and the deepest parts of the web in the past days trying to find a way to access button press from USB camera. I have one type of camera which uses HID driver and it was easy to access using node-hid library, however, I have another type which is a USB Composite driver camera that has a button on it, it works in the camera specific software and I'm trying to access the button trigger in an 'on data' type event using node-usb but replacing the drivers with WinUSB doesn't seem to work very well as I will need to distribute my software (which is built using Electron).

So far I have replaced the driver and succesfuly detected the USB and claimed an interface but the on event never trigger.

I'm looking for recommendations here on what diretion to take and starting to doubt if it's even possible without hacking drivers etc. I'm not closed to the idea of using Python or C# to make a command line that would watch for button events and send info to electron (if that's even possible) ?

**Comment by thegecko** [comment]
Sorry, we can't support implementation-specific issues
