### ISSUE TITLE
undefined symbol in v1.6.0

### ISSUE THREAD

**Issue by fridgerator** [node-usb/node-usb#322]
Using electron 3.0.10

node-usb v1.5.0 worked, however after upgrading to v1.6.0 I get this when I `require('usb')`:

`/path/to/project/node_modules/electron/dist/electron --inspect=5858 /path/to/project/dist/electron/main.js: symbol lookup error: /path/to/project/node_modules/usb/build/Release/usb_bindings.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
`

**Comment by thegecko** [comment]
This issue should be fixed since we moved to using `node-addon-api` and `prebuildify`. Please reopen this issue if it persists with the latest release.
