### ISSUE TITLE
Loading non-context-aware native module in renderer

### ISSUE THREAD

**Issue by xiaoxiangmoe** [node-usb/node-usb#380]
(node:82420) Electron: Loading non-context-aware native module in renderer: '/Users/foo/repos/app/node_modules/usb/build/Release/usb_bindings.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

**Comment by gniezen** [comment]
This should be resolved once #399 is merged.

**Comment by thegecko** [comment]
I believe this issue is fixed, please reopen if it persists with the latest release.
