### ISSUE TITLE
LIBUSB_ERROR_ACCESS on Windows using libusb0 (v1.2.40.201) default driver

### ISSUE THREAD

**Issue by jgcook935** [node-usb/node-usb#427]
I'm seeing issues running node-usb on Windows with the default libusb driver 1.2.40.201. This appears to be the driver which is auto installed by Windows, and is the most recent version. When you open Zadig to install the libusb v1.2.6.0 driver it shows as a downgrade instead of a replacement. I've seen slightly different symptoms when using this driver. In some cases we get LIBUSB_ERROR_ACCESS, an error claiming an interface, or 0's coming in from the stick when looking for ANT+ devices.

Does anyone have any ideas on how to get this driver working? Or any reason why the driver wouldn't work out of the box with libusb/node-usb? We're hoping to not request users to fiddle with their drivers prior to using software which depends on an older driver version.

Any information is appreciated,

Thanks!

**Comment by thegecko** [comment]
Perhaps the device has been claimed by another system?
