### ISSUE TITLE
Not Found 404 /releases/download/v1.7.2/usb-v1.7.2-electron-v75-win32-ia32.tar.gz

### ISSUE THREAD

**Issue by xvbo** [node-usb/node-usb#448]
prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.7.2/usb-v1.7.2-electron-v75-win32-ia32.tar.gz
 prebuild-install WARN install No prebuilt binaries found (target=7.3.3 runtime=electron arch=ia32 libc= platform=win32)
 packaging       platform=win32 arch=ia32 electron=7.3.3 appOutDir=dist\electron\win-ia32-unpacked

**Comment by thegecko** [comment]
We've switched to using Node-API for more recent builds, so this binary shouldn't be being requested. Can you confirm the node version you are using to build the application?

**Comment by xvbo** [comment]
> 请使用 v1.8.0 或更新版本重新测试，如果这解决了问题，请告诉我。

Its working for me.

Thanks

**Comment by thegecko** [comment]
Great!
