### ISSUE TITLE
LIBUSB Error Invalid Param

### ISSUE THREAD

**Issue by alexivaner** [node-usb/node-usb#462]
Hi, I got this error when using this library with [uvc-control](https://github.com/makenai/node-uvc-control), but I think that the error should be inside the USB library. I got an error like shown in the screenshot below "LIBUSB_ERROR_INVALID_PARAM". It happened when I used the original driver of my PTZ camera. I also tried to install WinUSB and this command worked fine, but the problem is if I replace the original driver with winusb, I could not access my PTZ Camera stream. It is necessary for me to be able to both control pan and zoom of my PTZ camera as well as access the camera streaming. Any way to obtain both of them? I will be really glad if someone could help. Many thanks.

node-usb version : tried both 2.0.3 and 1.9.2 reproduce the same result

![螢幕擷取畫面 2021-12-16 162435](https://user-images.githubusercontent.com/57290644/146341370-6dfc909e-9bef-4a1c-a8a4-4044408b72a4.png)

**Comment by thegecko** [comment]
The `uvc-control` library looks to be using a very old version of `node-usb` I'd recommend that gets upgraded and a reproducer shared here if the issue persists.
