### ISSUE TITLE
Using navigator.usb in the browser

### ISSUE THREAD

**Issue by gniezen** [node-usb/node-usb#466]
Hi there!

With node-usb v2 now supporting the WebUSB API, would it maybe be possible to have the library use `navigator.usb` when available? I would love to be able to use the same code in Node.js, Electron and the browser, and at the moment I'm having to use what feels like a hacky workaround:

```js
let isBrowser, usb = null;

if (typeof navigator !== 'undefined') {
  const userAgent = navigator.userAgent.toLowerCase();
  isBrowser = userAgent.indexOf(' electron/') === -1 && typeof window !== 'undefined';
} else {
  // Node.js process
  isBrowser = false;
}

if (!isBrowser) {
  // For Node.js and Electron
  const { webusb } = await import('usb');
  usb = webusb;
} else {
  usb = navigator.usb; // Yay, we're using WebUSB!
}
```

Instead, I would just like to do an `import { webusb } from 'usb';` and have it use `navigator.usb` in the browser and `node-usb` in Node.js and Electron.

**Comment by thegecko** [comment]
Hmm, interesting suggestion.

One drawback would be the user doesn't have control over which implementation is returned (but TBF, I can't think of an environment where both would be available).

**Comment by thegecko** [comment]
Something like #467?

**Comment by gniezen** [comment]
Yes, that looks like it will work just fine!
