### ISSUE TITLE
Does not support the ARM

### ISSUE THREAD

**Issue by dohooo** [node-usb/node-usb#472]
First many thanks to the great contributors for making such an amazing project. Thank you for your efforts! 🍺

Reproduce steps:
1.  git clone https://github.com/dohooo/node-usb-reproduction.git
1.  yarn
1. yarn watch

You will then see this error on the console, The code is here `/Users/zhaodonghao/code/temp/vite-electron-builder/packages/preload/src/sha256sum.ts`

Logs:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/32405058/151498170-466835c4-9e2f-433e-bba0-3506613aa435.png">

[localhost-1643350529203.log](https://github.com/node-usb/node-usb/files/7956261/localhost-1643350529203.log)

Does it look like the ARM compiled version is not found??  This mistake gives me a headache and I hope I can get help

**Comment by dohooo** [comment]
@thegecko 🙏

**Comment by dohooo** [comment]
Related with https://github.com/electron/electron/issues/32662

**Comment by thegecko** [comment]
Thanks for noticing this, it was an oversight
