### ISSUE TITLE
getEndpoint fails eagerly

### ISSUE THREAD

**Issue by pelikhan** [node-usb/node-usb#478]
I am in the process of porting our legacy node-webusb to node-usb and found this issue.

In `WebUSBDevice.getEndpoint`, there is a call to `iframe.endpoint(...)`
![image](https://user-images.githubusercontent.com/4175913/153081221-f1fbf905-efd9-493a-b999-890604cc4667.png)

This call fails eagerly instead of letting the loop go through
![image](https://user-images.githubusercontent.com/4175913/153081289-a5582e7d-3b01-4ef6-a870-65ac9f56d487.png)

This happens when we try to binding to endpointNumber 5 on a micro:bit v2.

**Comment by thegecko** [comment]
Thanks, I can see the problem. Will something like #479 fix you?

**Comment by pelikhan** [comment]
Yes that fixed it.
