### ISSUE TITLE
Can we use USB functions ?

### ISSUE THREAD

**Issue by Rutvij-dev** [node-usb/node-usb#482]
Hi,
Can we use this library to have Generic USB functions?

I am looking for the below functions 
1. USB Mass storage - Should be able to read/write
2. USB serial - serial consol
3. USB HID - Keyboard/mouse event
4. USB video class 

Any pointer or links will be appreciated. 

--
Thanks 
Rutvij

**Comment by thegecko** [comment]
This library is for low-level access as exposed by libusb.

For the higher level functionality you mention, I'd recommend looking at the following:

> USB Mass storage - Should be able to read/write

Use the node fs module, finding the usb mountpoint with a library such as:
https://github.com/thegecko/usb-mountpoint

> USB serial - serial consol

https://serialport.io/

> USB HID - Keyboard/mouse event

https://www.npmjs.com/package/node-hid

> USB video class

No idea!
