### ISSUE TITLE
Error in webusb-device.d.ts

### ISSUE THREAD

**Issue by daniloMogin** [node-usb/node-usb#484]
I'm getting this error while starting the application, and I just imported the library.

`node_modules/usb/dist/webusb/webusb-device.d.ts(6,22): error TS2720: Class 'WebUSBDevice' incorrectly implements class 'USBDevice'. Did you mean to extend 'USBDevice' and inherit its members as a subclass?
  Property 'forget' is missing in type 'WebUSBDevice' but required in type 'USBDevice'.`

**Comment by thegecko** [comment]
This was just fixed in #485 and the latest release (v2.1.3) should resolve the issue.

For older versions of node-usb, this should be fixable with a resolution to an older version of the webusb types:

```json
"resolutions": {
    "@types/w3c-web-usb": "1.0.5"
}
```
