### ISSUE TITLE
allow unreffing hotplug

### ISSUE THREAD

**Issue by mildsunrise** [node-usb/node-usb#497]
little feature request, very low priority, just here to remind myself in case I have time someday.

it would be cool if `usb` had `ref()` and `unref()` methods (like all Node.js event sources) to allow not holding the event loop alive. some projects may need it.

**Comment by thegecko** [comment]
Would that be similar to the hotplug ref/unref but for the [usb_context](https://github.com/node-usb/node-usb/blob/master/src/node_usb.cc#L15)?

**Comment by mildsunrise** [comment]
sorry, I can't make sense of this issue... as you mentioned, there's ref/unref for the hotplug events.
according to the history, it already existed when I opened this issue. really weird. anyway, closing.
