### ISSUE TITLE
Convert buffer to string/num?

### ISSUE THREAD

**Issue by unseen1980** [node-usb/node-usb#515]
Hello, thanks for the library!

I have a decibel meter and I am trying to read the values from the USB port. I found online how to do it but in Python. Because I am not familiar with Python I would prefer to use javascript or typescript. 

Please have a look at the screenshot below
![Screenshot 2022-05-20 at 17 21 53](https://user-images.githubusercontent.com/2386570/169570832-99ecf563-9e4f-4eb3-ba10-2c1743534f10.png)

The python script on the left works fine and I can see the values e.g. line 25 ```dB```.  Would you be able to help me with reading the data on the right typescript code? console.log shows data as a buffer. How can I convert it to a string or number? Buffer.from did not work for me.

Thanks a lot 👍

**Comment by kevinmehall** [comment]
You can access the bytes of a `Buffer` as if it were an array, (`data[0]`) just like in Python. How those bytes encode a particular status or measurement depends on the device. It looks like line 23 of your Python code to take the first byte and 2 bits of the second byte and apply a scale factor and offset would be basically the same syntax in JS.

**Comment by unseen1980** [comment]
Thanks a million, @kevinmehall, I wasn't aware of this. I can read the values now 👍
