### ISSUE TITLE
Poll Transfer - Start/Stop Poll

### ISSUE THREAD

**Issue by noah-moutfitters** [node-usb/node-usb#521]
## Bug Description:

Currently not able to make more than one poll transfer without closing the device.

Starting poll transfer has conditional:

```
        if (this.pollTransfers) {
            throw new Error('Polling already active');
        }
```

when no more polls are pending, it resets the state like so:

```
    if (_this.pollPending === 0) {
        _this.pollTransfers = [];
        _this.emit('end');
    }
```

The conditional needs to handle the case of an empty array, since any object in javascript is truthy. Another option is resetting the poll transfers to be undefined.  

I can create a PR for this. 

## Steps to Reproduce:
1. Open a usb device as normal
2. Start a poll transfer
3. Close said poll transfer
4. Wait for the end event to emit
5. Start another poll transfer

**Comment by thegecko** [comment]
A PR would be great!

**Comment by thegecko** [comment]
Does #522 fix you?

**Comment by noah-moutfitters** [comment]
@thegecko yes, thanks!

**Comment by noah-moutfitters** [comment]
@thegecko Do you also want the `pollActive` flag set to false when `pollsPending` equals 0? Seems like that may be desired behavior, it I’m unsure.

**Comment by thegecko** [comment]
Not sure, code was like this before I arrived ;)

**Comment by thegecko** [comment]
> @thegecko Do you also want the pollActive flag set to false when pollsPending equals 0? Seems like that may be desired behavior, but I’m unsure.

I added your suggestion, would you mind checking again?

**Comment by noah-moutfitters** [comment]
@thegecko Yes, thank you!
