### ISSUE TITLE
node-usb, inpoint.transfer. Can transfer write data to the keyboard through USB

### ISSUE THREAD

**Issue by kuangping-kp** [node-usb/node-usb#527]
var usb = require('usb');

      const GET_STATUS_INFO = 0x02;
      const data = [0x55, 0xff, 0x00, 0x00]
      var device = usb.findByIds(0x5566, 0x0008);
      console.log(device)
      var serialNumber = "2021-09-09"
      var s = usb.findBySerialNumber(serialNumber)
      console.log(s)
      if (device) {

        console.log('found  device');
        device.open();

        var interfaces = device.interfaces[0];
        console.log(interfaces)

        interfaces.claim();

        var inpoint = interfaces.endpoints[0]// interface.endpoint(id) don't work for id=0 btw

        var outpoint = interfaces.endpoints[0];

        console.log(inpoint)
        console.log(outpoint)

        var out_report = Buffer.alloc(32, 0);
        out_report[0] = GET_STATUS_INFO;

        console.log(out_report)

        inpoint.transfer(32, function (err, data, end) {
          if (data) {
            console.log(data)
          } else if (err) {
            console.log(err)

          } else {
            cconsole.log(end)
          }

        })
        console.log("222222222222222222")

        outpoint.transfer(0x02, 0x55, 0xff, 0x00, 0x00, function (err, end) {
          console.log("oooooooooooooooooooooooo")
          if (err) {

            console.log(err)
          }
          console.log(end)
        })
        console.log("33333333333333333")

      } else {
        console.log('USB Pendant not found');
        // process.exit(1);
      }

    }

**Comment by thegecko** [comment]
HID Devices should be accessed using a HID library such as `node-hid`.
