### ISSUE TITLE
Is there a recommended way to continuously read with WebUSB?

### ISSUE THREAD

**Issue by jeremywho** [node-usb/node-usb#553]
The legacy `StartPoll()`/`on("read", ...)` is very convenient, is there an established pattern for doing this with WebUSB?

**Comment by thegecko** [comment]
This could be a question to ask in the webusb spec:

https://github.com/WICG/webusb/issues/

Once a method for this (or intent) is understood, we can make sure this library supports it.

**Comment by mildsunrise** [comment]
polling an endpoint is just a matter of keeping N concurrent transfers alive at all times. the semantics of polling can vary so I wouldn't count on WebUSB adding a convenience method for that, instead this could be in a JS library
