### ISSUE TITLE
compile source to something more modern

### ISSUE THREAD

**Issue by jimmywarting** [node-usb/node-usb#604]
The generated source code and stack trace on errors are horrific to debug and do hot fixes inside of node_modules/usb/.

[looking](https://www.npmjs.com/package/usb?activeTab=code) at the source code in the dist folder is old-ish. I guess more modern code would ship less, work faster, and be easier to debug.

could you release some more modern ESM, es2022 variant or something else?
make some breaking changes

**Comment by NoahAndrews** [comment]
Looks like this can be closed, as #605 was merged
