### ISSUE TITLE
Error: Expected buffer for OUT transfer (based on bmRequestType) when executing clearHalt.

### ISSUE THREAD

**Issue by asivery** [node-usb/node-usb#635]
## Bug Description:
It seems like there's a problem with WebUSB API's clearHalt implementation. Executing clearHalt throws an error:

```
Expected buffer for OUT transfer (based on bmRequestType)
```

From what I understand, the error originates at:
https://github.com/node-usb/node-usb/blob/e9d33d81c495e33875b0dd85942af6335d85a27c/tsc/usb/device.ts#L137-L139

Which is called by:
https://github.com/node-usb/node-usb/blob/e9d33d81c495e33875b0dd85942af6335d85a27c/tsc/webusb/webusb-device.ts#L261

In this line, the value `0` is passed as `data_or_length`, but since it's an OUT request, `controlTransfer` expects a buffer and fails.

## Steps to Reproduce:
1. Execute clearHalt on a stalled endpoint of a WebUSB-API USB device.

## Additional Information
- Operating System: Ubuntu 22.04 
- Runtime (`node -v` or `electron -v`): Electron 13.6.9
- Node USB Version (`npm ls usb`): 2.4.3 (however it seems like it might still be present in the newest version)

**Comment by thegecko** [comment]
Yeah, I can see the issue.

Some possible ways to resolve this and keep the code clean:

- create a new transfer object in `clearHalt` and leave the device controlTransfer as is - duplicates code
- remove the length or buffer size check in device controlTransfer - loses a guard
- extend the data_or_length union type to also accept `false` to skip the checks

Thoughts or other suggestions?

cc @mildsunrise

**Comment by asivery** [comment]
@thegecko Why not create a new empty buffer in `clearHalt`, and pass that to `controlTransfer`?

**Comment by thegecko** [comment]
> @thegecko Why not create a new empty buffer in clearHalt, and pass that to controlTransfer?

I think that would only help with OUT endpoints. AFAICT the problem also exists for IN endpoints, too.

**Comment by asivery** [comment]
@thegecko Do you mean when using `clearHalt` on IN endpoints?
From what I understand, `clearHalt` is always an OUT control transfer. The actual endpoint is passed in `wIndex`. Feel free to correct me on that if I'm wrong please.

**Comment by thegecko** [comment]
> From what I understand, clearHalt is always an OUT control transfer. The actual endpoint is passed in wIndex. Feel free to correct me on that if I'm wrong please.

In this case your suggestion should work!

**Comment by thegecko** [comment]
How does #636 look?

**Comment by asivery** [comment]
@thegecko I think that it might fail because of what I mentioned above.
It doesn't matter if the endpoint you're running `clearHalt` on is an IN or OUT endpoint, clearHalt itself still goes through as an OUT control transfer.
The bug I'm reporting originated in this code:

https://github.com/asivery/node-mass-storage/blob/master/src/usb-mass-storage.ts#L158-L162

It's running `clearHalt()` on an IN endpoint, but the error was still 'Expected buffer for OUT transfer (based on bmRequestType)'

**Comment by thegecko** [comment]
Oh I see, I was assuming clearHalt gets called on the endpojnt being cleared, but it's actually on `LIBUSB_RECIPIENT_ENDPOINT`

PR updated accordingly.

**Comment by asivery** [comment]
@thegecko Looks good!
