### ISSUE TITLE
Code Examples

### ISSUE THREAD

**Issue by cstyan** [node-usb/node-usb#83]
Do you have an code examples you can add to the repo or README? Specifically for async reading from an inEndpoint using startPoll and piping the data from the transfer to another pipe.

**Comment by aGuyNamedJonas** [comment]
Second that! Thanks a lot for this library- getting into it is a lot faster with nice little examples, so those would be greatly appreciated! :)

**Comment by thegecko** [comment]
We have examples in the README now
